version: "3"
services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    apiproduit:
        build: 
            context: ./ApiProduit
            dockerfile: Dockerfile
        ports: 
            - "5020:80"
    apiuser:
        build: 
            context: ./ApiUser
            dockerfile: Dockerfile
        ports: 
            - "5010:80"